/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("war")
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.spring.webmvc)
    api(libs.org.thymeleaf.thymeleaf)
    api(libs.org.thymeleaf.thymeleaf.spring6)
    api(libs.com.h2database.h2)
    api(libs.org.springframework.data.spring.data.jdbc)
    providedCompile(libs.jakarta.servlet.jakarta.servlet.api)
}

group = "com.yandex.blog"
version = "1.0-SNAPSHOT"
description = "spring-web-app"
java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}


publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
