
ALTER TABLE "comment" DROP CONSTRAINT IF EXISTS "comment_fk0";
ALTER TABLE "post_preview" DROP CONSTRAINT IF EXISTS "post_preview_fk0";
DROP TABLE IF EXISTS "post" CASCADE;
DROP TABLE IF EXISTS "comment" CASCADE;
DROP TABLE IF EXISTS "post_preview" CASCADE;